//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SodaScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SodaScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Base_Profile {
            get {
                object obj = ResourceManager.GetObject("Base_Profile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close_Button {
            get {
                object obj = ResourceManager.GetObject("Close_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize_Button {
            get {
                object obj = ResourceManager.GetObject("Minimize_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nvidiaProfileInspector {
            get {
                object obj = ResourceManager.GetObject("nvidiaProfileInspector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pingtweaks {
            get {
                object obj = ResourceManager.GetObject("pingtweaks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Scheduled_Tasks {
            get {
                object obj = ResourceManager.GetObject("Scheduled_Tasks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SetTimerResolutionService {
            get {
                object obj = ResourceManager.GetObject("SetTimerResolutionService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Soda {
            get {
                object obj = ResourceManager.GetObject("Soda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap soda_can {
            get {
                object obj = ResourceManager.GetObject("soda-can", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon soda_can1 {
            get {
                object obj = ResourceManager.GetObject("soda_can1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set WshShell = CreateObject(&quot;WScript.Shell&quot;) 
        ///WshShell.Run chr(34) &amp; &quot;%windir%\System32\TempCleaner.bat&quot; &amp; Chr(34), 0
        ///Set WshShell = Nothing.
        /// </summary>
        internal static string TEMP22 {
            get {
                return ResourceManager.GetString("TEMP22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///del /s /f /q c:\windows\temp\*.*
        ///rd /s /q c:\windows\temp
        ///md c:\windows\temp
        ///del /s /f /q %temp%\*.*
        ///rd /s /q %temp%
        ///md %temp%
        ///deltree /y c:\windows\tempor~1
        ///deltree /y c:\windows\temp
        ///deltree /y c:\windows\tmp
        ///deltree /y c:\windows\ff*.tmp
        ///deltree /y c:\windows\history
        ///deltree /y c:\windows\cookies
        ///deltree /y c:\windows\recent
        ///deltree /y c:\windows\spool\printers
        ///del c:\WIN386.SWP
        ///cls.
        /// </summary>
        internal static string TempCleaner {
            get {
                return ResourceManager.GetString("TempCleaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon transparent {
            get {
                object obj = ResourceManager.GetObject("transparent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_pref(&quot;browser.chrome.site_icons&quot;, false);
        ///user_pref(&quot;full-screen-api.transition-duration.enter&quot;, 0);
        ///user_pref(&quot;full-screen-api.transition-duration.leave&quot;, 0);
        ///user_pref(&quot;full-screen-api.warning.timeout&quot;, 0);
        ///user_pref(&quot;nglayout.enable_drag_images&quot;, false);
        ///user_pref(&quot;browser.newtab.preload&quot;, false);
        ///user_pref(&quot;browser.tabs.crashReporting.sendReport&quot;, false);
        ///user_pref(&quot;security.certerrors.recordEventTelemetry&quot;, false);
        ///user_pref(&quot;security.app_menu.recordEventTelemetry&quot;, false);
        ///user_pref(&quot;net [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
